name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: sudo apt-get install -y libcurl4-openssl-dev uncrustify libyaml-dev
    - name: Cmake
      run: |
        cd kubernetes
        mkdir build
        cd build
        cmake ..
        make
    - name: Check
      run: ls -l kubernetes/build/libkubernetes.so
