name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        sudo apt-get install libcurl4-openssl-dev uncrustify libyaml-dev -y
        cd kubernetes
        mkdir build
        cd build
        cmake ..
        make
    - name: check
      run: ls -l kubernetes/build/libkubernetes.so
