name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        cd kubernetes
        mkdir build
        cd build
        cmake ..
        make
    - name: check
      run: ls -l libkubernetes.so
