name: Code Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [assigned, opened, synchronize, reopened]
jobs:
  code-stack-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Parepare
      run: sudo apt-get install -y cppcheck
    - name: Code static check for config
      run: sh ./code-check/code-static-check.sh ./kubernetes/config/
    - name: Code static check for examples
      run: sh ./code-check/code-static-check.sh ./examples/
  code-style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Parepare
      run: sudo apt-get install -y indent
    - name: Code style check for config
      run: find ./kubernetes/config/ -name "*.c" -exec sh ./code-check/code-style-check.sh {} \;
    - name: Code style check for examples
      run: find ./examples/ -name "*.c" -exec sh ./code-check/code-style-check.sh {} \;
