name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: code static check for config
      run: sh ./code-check/code-static-check.sh ./kubernetes/config/
    - name: code static check for examples
      run: sh ./code-check/code-static-check.sh ./examples/
