name: Code Static Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [assigned, opened, synchronize, reopened]
jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Parepare
      run: sudo apt-get install -y cppcheck
    - name: Code static check for config
      run: sh ./code-check/code-static-check.sh ./kubernetes/config/
    - name: Code static check for examples
      run: sh ./code-check/code-static-check.sh ./examples/
